# Generated by Django 5.2.5 on 2025-10-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('overview', 'Overview'), ('production', 'Production'), ('dispatch', 'Dispatch'), ('logistics', 'Logistics')], max_length=100)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
            ],
        ),
    ]
