# Generated by Django 5.2.5 on 2025-10-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-generated_on']},
        ),
        migrations.AddField(
            model_name='report',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
