# Generated by Django 5.2.5 on 2025-10-18 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_options_report_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='generated_on',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='data',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
        migrations.AddField(
            model_name='report',
            name='profit_or_loss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, choices=[('Profit', 'Profit'), ('Loss', 'Loss')], max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='total_dispatches',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='total_production',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='total_production_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='total_revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='total_transport_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
