# Generated by Django 5.2.5 on 2025-10-18 18:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='report',
            name='profit_or_loss',
        ),
        migrations.RemoveField(
            model_name='report',
            name='status',
        ),
        migrations.RemoveField(
            model_name='report',
            name='total_dispatches',
        ),
        migrations.RemoveField(
            model_name='report',
            name='total_production',
        ),
        migrations.RemoveField(
            model_name='report',
            name='total_revenue',
        ),
        migrations.RemoveField(
            model_name='report',
            name='total_transport_cost',
        ),
        migrations.AddField(
            model_name='report',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='total_dispatch_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='report',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='report',
            name='total_logistics_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='report',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='total_production_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
