# Generated by Django 5.2.5 on 2025-10-18 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_options_remove_report_profit_or_loss_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
    ]
