# Generated by Django 5.2.7 on 2025-10-15 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportcost',
            name='vehicle_no',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^K[A-Z]{2}-[0-9]{3}[A-Z]$')]),
        ),
    ]
