# Generated by Django 5.2.7 on 2025-10-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchrecord',
            name='tons_dispatched',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
