# Generated by Django 5.2.5 on 2025-10-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_alter_dispatchrecord_tons_dispatched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatchrecord',
            old_name='cost_of_tons_dispatched',
            new_name='cost_of_tons',
        ),
    ]
